---
- name: Установка PostgreSQL
  hosts: PosgreSQL
  become: true
  gather_facts: yes

  tasks:
    - name: Вывод информации об ОС
      debug:
        msg: "Операционная система: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Вывод информации о версии Python
      command: python3 --version
      register: python_version

    - name: Вывод версии Python
      debug:
        var: python_version.stdout
