all:
  children:
    BD:
      hosts:
        BD_1:
          ansible_host: 5.200.53.12
          ansible_playbook: ./templates/playbooks/PosgreSQL_install.yml
          ansible_ssh_pass: L6CUCijC
          ansible_user: root
        BD_2:
          ansible_host: 185.158.153.3
          ansible_playbook: ./templates/playbooks/PosgreSQL_install.yml
          ansible_ssh_pass: AMpqY42X
          ansible_user: root
    Backend:
      hosts:
        Backend_1:
          ansible_host: 5.200.35.16
          ansible_playbook: ./templates/playbooks/Django_install.yml
          ansible_ssh_pass: tcQr0vwZ
          ansible_user: root
    Nginx:
      hosts:
        Nginx_1:
          ansible_host: 5.200.35.31
          ansible_playbook: ./templates/playbooks/Nginx_install.yml
          ansible_ssh_pass: 6y7PaURL
          ansible_user: root
        Nginx_2:
          ansible_host: 185.158.152.23
          ansible_playbook: ./templates/playbooks/Nginx_install.yml
          ansible_ssh_pass: Buf8QZQ9
          ansible_user: root
