Create_server_answer = {
    'ID': 962767, 
    'Name': 'testapi1', 
    'HostName': None, 
    'State': 'New', 
    'IsPowerOn': False, 
    'CPU': 2, 
    'RAM': 2048, 
    'HDD': 40, 
    'IP': '', 
    'AdminUserName': None, 
    'AdminPassword': None, 
    'Image': 'WinServer2012R2x64En', 
    'IsHighPerformance': False, 
    'HDDType': 'SSD', 
    'PrimaryNetworkIp': '', 
    'LinkedNetworks': [], 
    'DCLocation': 'SdnSpb', 
    'ImageFamily': 'Windows', 
    'LinkedSshKeys': [], 
    'DateCreate': '2023-05-13T16:57:15.495094+03:00'
    }